version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - service1
      - service2
    networks:
      - app-network

  service1:
    build: ./service_1
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 4

  service2:
    build: ./service_2
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge
